_target_: agents.encoders.multi_image_obs_encoder.MultiImageObsEncoder
_recursive_: false

shape_meta: ${shape_meta}

rgb_model:
  _target_: agents.encoders.resnets.BesoResNetEncoder
  latent_dim: ${latent_dim}

resize_shape: null
#    crop_shape: [ 84, 84 ]
# constant center crop
random_crop: False
use_group_norm: True
share_rgb_model: False
imagenet_norm: True